// Generated by しくみや — 2026-04-05T03:08:20.520Z
export const siteConfig = {
  name: "Lyo",
  siteTitle: "Lyoのアートギャラリー",
  description: "AI画像生成初めて約3年経ったけど、全然うまくいかない",
  url: "",
  lang: "ja",
  template: "ink-wash",

  colors: {
    primary: "#8DC8E8",
    accent: "#C4B5E0",
    background: "#ffffff",
  },

  hero: {
    tagline: "Gallery",
    catchcopy: "人と人を繋ぐ",
    motto: "人と人を繋ぐ",
    subtitle: "Art Portfolio",
    description: "AI画像生成初めて約3年経ったけど、全然うまくいかない",
    backgroundImage: "/images/hero.webp",
    cta: {
      text: "作品を見る",
      href: "#gallery",
    },
  },

  gallery: {
    title: "GALLERY",
    subtitle: "作品ギャラリー",
    description: "",
    works: [
    { src: "/images/work_02.webp", title: "作品 01", description: "" },
    { src: "/images/work_03.webp", title: "作品 02", description: "" },
    { src: "/images/work_04.webp", title: "作品 03", description: "" },
    { src: "/images/work_05.webp", title: "作品 04", description: "" },
    { src: "/images/work_06.webp", title: "作品 05", description: "" },
    { src: "/images/work_07.webp", title: "作品 06", description: "" },
    { src: "/images/work_08.webp", title: "作品 07", description: "" },
    { src: "/images/work_09.webp", title: "作品 08", description: "" },
    ],
    initialDisplay: 8,
    columns: 4,
  },

  about: {
    title: "ABOUT",
    subtitle: "アーティストについて",
    image: "/images/about.webp",
    paragraphs: ["AI画像生成初めて約3年経ったけど、全然うまくいかない"],
    quote: "人と人を繋ぐ",
    genres: [],
    tools: [],
  },

  contact: {
    title: "CONTACT",
    subtitle: "お問い合わせ・SNS",
    description: "お仕事のご依頼・コラボレーション・ご質問はお気軽にどうぞ。",
    email: "ryoya112@outlook.com",
    social: [
    { label: "X (Twitter)", href: "https://x.com/tohkaai?s=21&t=X2NTXj7ncxDYhkSWUJ_dig" },
    ] as { label: string; href: string }[],
  },

  nav: [
    { label: "Gallery", href: "#gallery" },
    { label: "About", href: "#about" },
    { label: "Contact", href: "#contact" },
  ],

  footer: {
    credit: "Built with Next.js — Template by しくみや",
    copyright: `© ${new Date().getFullYear()} Lyo. All rights reserved.`,
  },
};

export type SiteConfig = typeof siteConfig;
